@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 20

box "Government"
  participant "Corporate Registry" as Registry
  participant "WSA" as WSA
endbox
participant "Building Owner" as Owner


box "Acme Construction Inc."
  participant "Company" as Acme
  actor "Employee" as Employee
endbox

box "City"
  participant "Permits Dept" as City
  actor "Inspector" as Inspector
endbox




=== Story 1 - Acme Registers with Corporate Registry ==
Acme -> Registry: Request Corporate Registration
Registry -> Registry: internal
Registry -> Acme: Send Corporate Registration
Acme -> Acme: Store Corp Registration






=== Story 2 - Acme Obtains WSA Clearance Letter ==

Acme -> Acme: Assemble CL applications
Acme -> WSA: Send CL Application Request
WSA -> WSA: Confirm application detail and assemble CL
WSA -> Acme: Send Clearance Letter <vCL>
Acme -> Acme: Store Clearance Letter
Acme -> WSA: Subscribe to Revocation for CLID
WSA -> Acme: Confirm subscription




=== Story 3 - # Home Addition Project ==
note over Owner, City
  A Homeowner has decided to add an extension to her residential home.
  After completing her financial and architectural dependencies she
  obtains a Residential Building Permit from the City Building Department.
  She has also contracted with Acme Construction Company for the project.
  When the work commences she needs to verifies Acme employees that arrive
  onsite each day for Acme credentials which include proof of employment
  as well as Acme's WSA clearance letter.
end note

Owner -> Owner: Assemble building permit package
Owner -> City: Request Building Permit
City -> City: Analyze and Approve
City -> Owner: Send Building Permit <vPermit>
Owner -> Owner: Store vPermit



=== Story 4 - Acme Provides Clearance Letter For Authorized Employees ==
Acme -> Employee: Send copy of Clearance Letter <vCL>
Employee -> Employee: Store vCL



=== Story 6 - Commercial Building Permit Acquisition==
note over Owner, City
The entity owning a new shopping plaza has registered with the corporate registry.
The owner of a new shopping plaza has just received financial and architectural
approvals for proceeding with the project. He obtains a new Commercial
Building Permit from the City Building Department.

end note
Owner -> Owner: Assemble building permit package
Owner -> City: Request Building Permit
City -> City: Analyze and Approve
City -> Owner: Send Building Permit <vPermit>
Owner -> Owner: Store vPermit

=== Story 5 - City Inspector Performs Site Inspection ==
note over Owner, City
  City Inspector arrives at home owner's job site to perform inspection. First
  step is to validate that the required building permit is in place and that
  the contractors on site are covered by Workplace Safety Agency (WSA) insurance.

  City Inspector requests building permit from home owner, receiving a digital
  copy of the building permit. Inspector requests Contractor's WSA Clearance
  Letter from Home Owner for Acme and that each job site employee works for
  Acme. Permit, Clearance Letter, and Employee Badges are proved (as valid).
end note

Inspector -> Owner: Requests information package
Owner -> Inspector: provides copy of Clearance Letter
Owner -> Inspector: provides copy of Building Permit




=== Story 7 Acme Assigns An Employee to the Home Addition Project ==
Acme -> Acme: Assemble Employee Badge info package
Acme -> Employee: Send vBadge
Employee -> Employee: Store vBadge


=== Story 8 - Home Owner Verifies Contractor ==
Owner -> Acme: Request Clearance Letter
Acme -> Owner: Provide copy of vCL
Owner -> Owner: Store vCL
Owner -> WSA: Subscribe for Revocation Notification
WSA -> Owner: Confirm sub
loop for each Employee of Acme
  Owner-> Employee: Request vBadge
  Employee -> Owner: Provide vBadge
  Owner -> Owner: Verify vBadge is Acceptable
end

=== Story 9 - Contractor Verifies Home Owner ==


=== Story 10 - WSA Inspector Performs Site Inspection ==


=== WSA Revokes CL ==
note over WSA, Acme
  Advise subscribers of Revocation
end note

WSA -> Owner
WSA -> Acme

@enduml