@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 20

=== Get Commercial Building Permit ==
participant "Corporate Registry" as Registry
participant "Building Owner" as Owner
participant "Contractor" as Acme
participant "City" as City
participant "WSA" as WSA

note left

end note

Owner -> Owner: Assemble Permit Package
Owner -> City: Apply for permit <PermitApplicationPackage>
City  -> City: confirm information
City -> Owner: Send Building Permit <PermitClaim>

=== ACME Corporate Registration ==
Acme -> Registry: Request Corporate Registration
Registry -> Registry: internal
Registry -> Acme: Send Corporate Registration
Acme -> Acme: Store Corp Registration




=== ACME Certification (Clearance Letter) ==
Company -> Company: Assemble CL package
Company -> WSA: Request Clearance Letter <CLRequest>
WSA -> WSA: Internal Steps
WSA -> Company: Issue Clearance Letter <vClearanceLetter>
Company -> Company: Store Clearance Letter
rnote over WSA
  Clearance Letter Conditions is Updated
endrnote

WSA -> Company: Revoke old CL

Company -> WSA: Reu

@enduml